# Generated by Django 2.2.5 on 2019-09-21 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('bonus_code', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('fas_time', models.DateTimeField()),
                ('type', models.CharField(max_length=128)),
            ],
        ),
    ]
