# Generated by Django 2.2.5 on 2019-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='fas_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
